name: cookery_book
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.14.0
  input_quantity: ^2.5.1
  collection: ^1.19.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  path: ^1.9.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/menu.json
